---
- name: "Generating script from template <<For kafka:{{item}}>>"
  template:
   src: CheckKafkaPort.j2
   dest: "{{role_path}}/files/CheckKafkaPort.sh"
   owner: jenkins
   group: jenkins
   mode: 0644
  delegate_to: localhost

- name: "Copy supporting script on remote server <<For kafka:{{item}}>>"
  copy:
   src: files/CheckKafkaPort.sh
   dest: /tmp/CheckKafkaPort.sh
   mode: 700
   owner: jenkins
   group: jenkins
  become: true

- name: "Checking port availability <<For kafka:{{item}}>>"
  shell: /tmp/CheckKafkaPort.sh
  register: KafkaPortOutput
  #failed_when: false
  changed_when: false
  become: true

#- debug: msg="{{KafkaPortOutput}}"

- name: "Generating server{{item}}.properties from template  <<For kafka:{{item}}>>"
  template:
   src: server.properties.j2
   dest: "{{role_path}}/files/server{{item}}.properties"
   owner: jenkins
   group: jenkins
   mode: 0644
  delegate_to: localhost

- name: "Copy server{{item}}.properties on remote server <<For kafka:{{item}}>>"
  copy:
   src: "files/server{{item}}.properties"
   dest: "{{KafkaSoftDir}}/config/server{{item}}.properties"
   mode: 0700
   owner: jenkins
   group: jenkins
  become: true

- name: "Starting Kafka:{{item}}"
  shell: "nohup {{SoftwareStopStart[SoftwareName]['StartScript']}} ../config/server{{item}}.properties >{{SoftwareStopStart[SoftwareName]['BinDir']}}/Kafka{{item}}_startup.log 2>&1 &"
  args:
   chdir: "{{SoftwareStopStart[SoftwareName]['BinDir']}}"
